name: FallenStar-UI
version: ${project.version}
main: de.fallenstar.ui.UIModule
api-version: '1.21'
authors: [FallenStar]
description: UI-Modul mit konkreten UIs (Confirmation, Trade, Dialog, etc.)

# Hard dependency on Core
depend:
  - FallenStar-Core

# Soft dependencies (optional)
softdepend: []

# Permissions
permissions:
  fallenstar.ui.admin:
    description: Admin-Zugriff auf UI-Testbefehle
    default: op
