name: FallenStar-NPCs
version: ${project.version}
main: de.fallenstar.npc.NPCModule
api-version: 1.21
authors: [FallenStar]
description: NPC management system with specialized NPCs

# Abhängigkeiten
depend: [FallenStar-Core, FallenStar-Economy]
softdepend: [Towny, Citizens, Vault]
