name: FallenStar-Plots
version: 1.0-SNAPSHOT
main: de.fallenstar.plot.PlotModule
api-version: 1.21
authors: [FallenStar]
description: Plot management and NPC spawning system

# Abhängigkeiten
depend: [FallenStar-Core, Towny, FallenStar-UI]
softdepend: [Citizens]

# Commands werden über Towny Command Addon API registriert
# Kein eigener /plot Command - wir erweitern Townys /plot
